name: Preview

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          comment: true
          qr-target: 'expo-go'
          working-directory: ${{ github.workspace }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
